### ISSUE TITLE
关于jshunter工具的问题

### ISSUE THREAD

**Issue by kaynewu** [codeskyblue/jshunter#1]
现在jshunter工具是否支持xml格式或者json格式的报告输出形式呢？
添加自定义检查规则有哪些具体步骤是怎样的？
能不能给个罗列一下jshunter有哪些error，warning级别的错误？
希望能在github上看到这些信息，更有助于帮助大家理解使用jshunter这个工具

**Comment by codeskyblue** [comment]
README.md我更新了下。具体的配置很多，可以看下hint.conf中的注释，修改配置项就可以修改过滤项了。结合注释方便理解。
