### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by kaynewu** [codeskyblue/jshunter#2]
执行工具的该命令时出现如下错误
jshunter-master/core> v8-shell-32
Floating point exception
这是什么原因导致的呢？换了好几台机器都是同样的问题

**Comment by codeskyblue** [comment]
@kaynewu 土豪啊， 你这么多机器。 
你的机器是多少位的啊。 实在不好弄按照上面的方法 http://www.myexception.cn/linux-unix/788477.html，手工编译出来一个v8-shell, 把那个程序替换掉，就OK了

**Comment by kaynewu** [comment]
唉编译失败啊，你的v8shell是自己编译的还是在哪下的？

**Comment by codeskyblue** [comment]
自己编译的。
